name: example
version: 0.0.1
description: An example for envify.
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  envify:

dev_dependencies:
  build_runner: ^2.3.3
  envify_generator:

dependency_overrides:
  envify:
    path: ../envify
  envify_generator:
    path: ../envify_generator
